kkn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('koloid.urls')),
]

koloid/urls.py
from django.urls import path
from . import views

app_name = 'koloid'

urlpatterns = [
    path('', views.index, name='index'),
    path('materi/', views.materi, name='materi'),
    path('sifat-koloid/', views.sifatkoloid, name='sifatkoloid'),
    path('jenis-koloid/', views.jeniskoloid, name='jeniskoloid'),
    path('pembuatan-koloid/', views.pembuatankoloid, name='pembuatankoloid'),
    path('soal/', views.soal, name='soal'),
    path('video/', views.video, name='video'),
    path('games/', views.games, name='games'),
    path('tentang-kami/', views.tentangkami, name= 'tentangkami'),
]

koloid/models.py
from django.db import models

# Create your models here.

koloid/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')
def materi(request):
    return render(request, 'materi.html')
def sifatkoloid(request):
    return render(request, 'sifatkoloid.html')
def jeniskoloid(request):
    return render(request, 'jeniskoloid.html')
def pembuatankoloid(request):
    return render(request, 'pembuatankoloid.html')
def soal(request):
    return render(request, 'soal.html')
def video(request):
    return render(request, 'video.html')
def games(request):
    return render(request, 'games.html')
def tentangkami(request):
    return render(request, 'tentangkami.html')

koloid/templates/games.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body>
     <h1 id="judul">INI YANG D</h1>
     <p id="salsa">Website ini berisi tentang pembelajaran kimia untuk KKN</p>
     <img src="{% static 'images/20.jpg' %}" alt="CGT" height="300" width="400"> 
 </body>  
</html>
{% endblock %}

koloid/templates/index.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body>
     <div class="container-fluid">
        <p id="kosong"> .</P>
            <h2 id="monangis">KAMI DISINI UNTUK MEMBANTU ANDA</h2> 
            <h1 id="semangat">SELAMAT DATANG DI CHEMSROOM</h1>
            <h3 id="jargon">jargon</h3>
          <div class="row">
              <div class="col-md-12">
              </div>
          </div>
          <div class="row">
              <div class="col-md-12">
              </div>
          </div>
          <div class="row">
              <div class="col-md-12">
              </div>
          </div>
     </div>

 </body> 
 
</html>
{% endblock %}

koloid/templates/jeniskoloid.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}

{% endblock %}

koloid/templates/materi.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body>
     <h1 id="judul">>INI YANG A</h1>
     <p id="salsa">Website ini berisi tentang pembelajaran kimia untuk KKN</p>
     <img src="{% static 'images/20.jpg' %}" alt="CGT" height="300" width="400"> 
 </body>  
</html>
{% endblock %}

koloid/templates/menu.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>KKN ONLINE</title>
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
       
    </head>
<nav class="navbar navbar-expand-lg navbar-dark abc">
    <div class="topnav">
        <a class="navbar-brand" href="{% url 'koloid:index' %}"><img src="{% static 'images/output-onlinepngtools-6.png'  %}" height = "60px" width ="60px" id="topright"></a>
        <img src="{% static 'images/Logo-UNJ-Universitas-Negeri-Jakarta-Original.png'  %}" height = "50px" width ="50px" id="topright2">
        <button class="navbar-toggler" id="colorr" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse navbarrr" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-link dropdown">
                <a class="nav-link dropdown-toggle navbarrr" id="warna" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    materi
                </a>
                    <div class="dropdown-menu navbarrr" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item navbarrr" href="/sifat-koloid">sifat koloid</a>
                        <a class="dropdown-item navbarrr" href="/jenis-koloid">jenis koloid</a>
                        <a class="dropdown-item navbarrr" href="/pembuatan-koloid">pembuatan koloid</a>
                    </div>
                </li>
                <li class="nav-link">
                    <a class="nav-link" id="warna" href="/soal" target="_blank">soal</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" id="warna" href="/video" target="_blank">video</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" id="warna" href="/games" target="_blank">games</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" id="warna" href="/tentang-kami" target="_blank">tentang kami</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<div class="backgroud" style="background-image: url({% static 'images/bgggg.png' %});">
{% block content %}
{% endblock %}
</html>

koloid/templates/pembuatankoloid.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}

{% endblock %}

koloid/templates/sifatkoloid.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
    <body>
        <h1 id="judulsifatkoloid">
            SIFAT KOLOID
        </h1>
        <p id="biarsifatkoloidketengah">
            .
        </p>
        <div class="row isisifatkoloid">
            <div class="col-md-12">
                <h2>
                    1.	Efek Tyndall
                </h2>
                <p id="fontisisifatkoloid">
                    Efek Tyndall merupakan efek penghamburan berkas sinar (cahaya) oleh partikel-partikel koloid. Hal ini disebabkan karena ukuran pertikel koloid yang cukup besar. Efek tyndall ini ditemukan oleh John Tyndall (1820-1893), seorang ahli fisika Inggris. Pada saat larutan disinari dengan cahaya, maka larutan tersebut tidak akan menghamburkan cahaya, sedangkan pada sistem koloid cahaya akan dihamburkan. Hal tersebut terjadi karena partikel-partikel koloid mempunyai partikel yang relatif besar untuk dapat menghamburkan sinar tersebut. Sebaliknya, pada larutan sejati, partikel-partikelnya relatif kecil sehingga hamburan yang terjadi hanya sedikit dan sangat sulit diamati.
                </p>
                <img id="gambarsifatkoloid" src="{% static 'images/Efek tyndall.png'  %}">
                <h2>
                     2.	Gerak Brown
                </h2>
                <p>
                    Gerak brown adalah gerak acak, gerak tidak beraturan, atau gerak zigzag partikel koloid. Gerakan ini terjadi akibat adanya tumbukan partikel pendispersi terhadap partikel terdispersi. Jika diamati dibawah mikroskop ultra, maka akan terlihat bahwa partikel-partikel tersebut bergerak membentuk zigzag. 
                </p>
                <p>
                    Semakin kecil ukuran partikel koloid, maka semakin cepat gerak brown yang terjadi. Demikian pula, semakin besar ukuran partikel koloid, semakin lambat gerak brown yang terjadi. Gerak brown juga dipengaruhi oleh suhu. Semakin tinggi suhu sistem koloid, maka semakin besar energi kinetik yang dimiliki partikel-partikel medium pendispersinya. Akibatnya, gerak brown dari partikel-partikel fase terdispersinya semakin cepat. 
                </p>
                <p>
                    Contoh gerak brown dalam kehidupan sehari-hari yaitu pada susu. Apabila susu didiamkan dalam waktu beberapa lama, tidak akan terdapat endapan. Hal ini disebabkan karena adanya gerak terus-menerus secara acak yang dilakukan oleh partikel-partikel koloid dalam susu.
                </p>
                <img id="gambarsifatkoloid" src="{% static 'images/Gerak brown 1.png'  %}">
                <img id="gambarsifatkoloid" src="{% static 'images/Gerak brown 2.png'  %}">
                <h2>
                    3.	Adsorpsi
                </h2>
                <p>
                    Adsorpsi peristiwa penyerapan partikel atau ion atau senyawa lain pada permukaan partikel koloid yang disebabkan oleh luasnya permukaan partikel. Zat yang diserap disebut adsorbat dan zat yang menyerap disebut adsorben. Peristiwa adsorpsi disebabkan oleh gaya tarik molekul pada permukaan adsorben. Contoh adsorpsi pertama, pada koloid Fe(OH)3 yang bermuatan positif karena permukaannya menyerap ion H+. Contoh berikutnya pada koloid As2S3 yang bermuatan negatif karena permukaannya menyerap ion S2+.
                </p>
                <img id="gambarsifatkoloid" src="{% static 'images/Adsorpsi 1.png'  %}">
                <img id="gambarsifatkoloid" src="{% static 'images/Adsorpsi 2.png'  %}">
                <h2>
                    4.	Koagulasi
                </h2>
                <p>
                    Koagulasi merupakan peristiwa pengendapan atau penggumpalan koloid. Dengan terjadinya koagulasi, berarti zat terdispersi tidak lagi membentuk koloid. Jika muatan koloid dihilangkan, maka kestabilannya akan berkurang sehingga dapat menyebabkan koagulasi atau penggumpalan. Waktu koagulasi koloid bervariasi antara yang satu dengan yang lain. Koagulasi spontan umumnya lambat dan dapat dipercepat dengan alat sentrifugal ultra. Alat ini akan memutar koloid dengan kecepatan tinggi sehingga partikel didorong ke dasar tabung reaksi.
                </p>
                <img id="gambarsifatkoloid" src="{% static 'images/Koagulasi.png'  %}">
                <h2>
                    5.	Koloid Pelindung 
                </h2>
                <p>
                    Koloid pelindung meupakan koloid yang mempunyai sifat yang dapat melindungi koloid lain dari proses koagulasi.
                </p>
                <h2>
                    6.	Dialisis
                </h2>
                <p>
                    Dialisis merupakan proses pemurnian koloid yang didasarkan pada perbedaan ukuran partikel. Dialisis juga dapat diartikan proses pemisahan koloid dari ion-ion pengganggu, yaitu dengan mengalirkan cairan yang tercampur dengan koloid melalui membran semi permeable yang berfungsi sebagai penyaring. Membran semi permeable ini dapat dilewati cairan tetapi tidak dapat dilewati koloid, sehingga koloid dan cairan akan berpisah.
                </p>
                <img id="gambarsifatkoloid" src="{% static 'images/dialisis.png'  %}">
                <h2>
                    7.	Elektroforesis
                </h2>
                <p>
                    Elektroforesis merupakan peristiwa bergeraknya partikel koloid dalam medan listrik yang bergerak ke arah elektroda berlawanan. Contoh elektroforesis dalam kehidupan sehari-hari yaitu pada industri mobil, saat proses pengecatan badan mobil dialiri cairan bermuatan yang berlawanan sehingga cat dapat menempel dengan sempurna.
                </p>
            </div>
        </div>
    </body>
</html>
{% endblock %}

koloid/templates/soal.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body>
    <p> 1. Diberikan beberapa cara pembuatan koloid berikut.
        <p>
            (1) busur Bredig
        </p>
        (2) mekanik
        (3) peptisasi
        (4) reaksi hidrolisis
        (5) reaksi dekomposisi rangkap
        Pembuatan koloid secara dispersi adalah…..
        A. (1), (2), (3)
        B. (1), (2), (5)
        C. (1), (3), (5)
        D. (2), (3), (4)
        E. (2), (3), (5)
        </p>
 </body>  
</html>
{% endblock %}

koloid/templates/tentangkami.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body>
     <h1 id="judul">>INI YANG E</h1>
     <p id="salsa">Website ini berisi tentang pembelajaran kimia untuk KKN</p>
     <img src="{% static 'images/20.jpg' %}" alt="CGT" height="300" width="400"> 
 </body>  
</html>
{% endblock %}

koloid/templates/video.html
{% extends 'menu.html' %}
{% load static %}
{% block content %}
<html>
 <body id="bgvideo">
     <div class="row">
         <div class="col-md-12">
             <h1 id="judul">Apa itu koloid?</h1>
         </div>
     </div>
     <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
            <video id="video1" width="720" height="480" controls>
                <source src="{% static 'videos/Apa itu Koloid – Kimia Kelas XI.mp4'  %}" type="video/mp4">
              Your browser does not support the video tag.
            </video>
            <p>source: <a href="https://youtu.be/QLjMB2YSgWQ" target="_blank">Youtube/DaniRizky</a> 
            </p>
        </div>
        <div class="col-md-3"></div>
     </div>


    <div class="row">
        <div class="col-md-12">
            <h1 id="judul">Pengertian Koloid</h1>
        </div>
    </div>
    <div class="row">
       <div class="col-md-3">
       </div>
       <div class="col-md-3">
           <video id="video1" width="720" height="480" controls>
               <source src="{% static 'videos/Pengertian Koloid.mp4'  %}" type="video/mp4">
             Your browser does not support the video tag.
           </video>
           <p>source: <a href="https://youtu.be/dm-a4d5-NrA" target="_blank">Youtube/ChemistryEcha</a> 
           </p>
       </div>
       <div class="col-md-3"></div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h1 id="judul">Jenis-Jenis Koloid</h1>
        </div>
    </div>
    <div class="row">
       <div class="col-md-3">
       </div>
       <div class="col-md-3">
           <video id="video1" width="720" height="480" controls>
               <source src="{% static 'videos/Jenis-Jenis Koloid.mp4'  %}" type="video/mp4">
             Your browser does not support the video tag.
           </video>
           <p>source: <a href="https://www.youtube.com/watch?v=rFxvsxsjYN8&feature=youtu.be" target="_blank">Youtube/ChemistryEcha</a> 
           </p>
       </div>
       <div class="col-md-3"></div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h1 id="judul">Sifat-Sifat Koloid</h1>
        </div>
    </div>
    <div class="row">
       <div class="col-md-3">
       </div>
       <div class="col-md-3">
           <video id="video1" width="720" height="480" controls>
               <source src="{% static 'videos/Sifat-Sifat Koloid.mp4'  %}" type="video/mp4">
             Your browser does not support the video tag.
           </video>
           <p>source: <a href="https://youtu.be/hc-0bY9bMR8" target="_blank">Youtube/RenySeptiani</a> 
           </p>
       </div>
       <div class="col-md-3"></div>
    </div>
 </body>  
</html>
{% endblock %}